site_name: Exposición
dev_addr: 127.0.0.1:8003
# site_url: 
# repo_url: 
# repo_name: <i class="fa fa-git"></i>

theme:
    name: mkdocs
    custom_dir: resources/
extra_css:
    - css/page.css
nav:
    - Modelo paracurricular de NYCE:
        - ¿Qué es un modelo paracurricular?: ModeloParacurricular.md
    - NYCE:
        - NYCE: NYCE.md
        - Servicios: Servicios_NYCE.md 

    - NYCE y las TI:
        - NYCE y las TI: NYCEyLasTI.md
    - Normas de NYCE:
        - ISO/IEC_29110-4-1:2018(PERFIL BÁSICO): ISOIEC_29110-4-1_2018_PerfilBasico.md
copyright: ©GMDXX
site_author: GMDXX

