site_name: Actividades
dev_addr: 127.0.0.1:8001
# site_url: 
# repo_url: 
# repo_name: <i class="fa fa-git"></i>

theme:
    name: mkdocs
    custom_dir: resources/
extra_css:
    - css/page.css
nav:
    - Modelo paracurricular de NYCE:
        - ¿Qué es un modelo paracurricular?: ModeloParacurricular.md
    - NYCE:
        - NYCE: NYCE.md

    - NYCE y la Ingeniería de Software:
        - NYCE y la Ingeniería de Software: NYCEyLaIngenieriadeSoftware.md

copyright: ©GMDXX
site_author: GMDXX
